version: '3.8'

services:
  app:
    image: inventory-app
    build:
      context: .
    ports:
      - "8010:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=db_inventory
      - DB_USERNAME=otuser
      - DB_PASSWORD=otadmin

  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: db_inventory
      MYSQL_USER: otuser
      MYSQL_PASSWORD: otadmin
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
